### ISSUE TITLE
Multi-Tenant

### ISSUE THREAD

**Issue by poxin13** [chises/zabbix-nakivo#1]
Doesn't appear to work if you have multi-tenancy. Job list JSON reports back as empty

**Comment by chises** [comment]
@poxin13 are you still using nakivo? Could you grab the new screipt and execute it, and come back with the result here? I dont have access to multi-tenancy installations, but i think we can solved this together :)

**Comment by chises** [comment]
Close because of complete rework and no feedback.

**Comment by Elkropac** [comment]
Hi, i wil try to make support for MT operation, we need to start monitoring our nakivo instances. I will make PR if i manage to pull it off
