### ISSUE TITLE
Not sure if working

### ISSUE THREAD

**Issue by Kjoffy** [chises/zabbix-nakivo#2]
Not sure how to test, All errors for finding the file and JSON has been resolved. (under the Info TAB)

But it is not giving any information back, did some test runs on Nakivo but no information is showing anywhere in my zabbix environment.

Any tips if it works for Nakivo version Version: 9.1.0 (build 39501)

**Comment by chises** [comment]
@Kjoffy I am sorry for the late response! A complete rework is available. Only cli.sh and cli.jar from nakivo server is required. Could you install this one and check if everything is working?

**Comment by chises** [comment]
Close because of complete rework and no feedback.

**Comment by Kjoffy** [comment]
It Works!!

Tested with Zabbix 6.2.6 and Nakivo 10.7.2 & Nakivo 10.6.0

**Comment by chises** [comment]
Great, 👍 thank you for your feedback 😊

**Comment by Kjoffy** [comment]
Any idea what the JSON Path and Javascript Parameters should be when working with --Repository-list
I want to display the repository name/health/space in zabbix.

**Comment by chises** [comment]
I will check it tomorrow :)

**Comment by chises** [comment]
@Kjoffy please track the feature request on #5
