### ISSUE TITLE
nakivo.sh: 13: Syntax error: redirection unexpected

### ISSUE THREAD

**Issue by mrowec** [chises/zabbix-nakivo#6]
When I start script nakivo.sh:
sh nakivo.sh 129.168.2.211 admin password

I got:
nakivo.sh: 13: Syntax error: redirection unexpected

and second question about "()" on line 8 in https://github.com/chises/zabbix-nakivo/blob/master/nakivo.sh is correct ?

**Comment by mrowec** [comment]
https://github.com/chises/zabbix-nakivo/blob/d01e3963b3fd0a094beb7a0f48c6517ba0fa6882/nakivo.sh#L13

**Comment by mrowec** [comment]
sorry i have make mistake. i should use ./nakivo.sh instead of sh nakivo.sh. now its start script correctly.
but when you are testing script from cli you should enter 4 parameters, last one should be job OR repository

event that now I got timedout:

connecttimedout(SocketTimeoutException)

port 4443 as parameter I hardcoded to script

**Comment by chises** [comment]
@mrowec sorry for the late response, I were on holiday ;)
sh nakivo.sh is not working
please try 
bash nakivo.sh this works

I am going to add a check that the script is executed directly or by "bash" instead of sh to "bypass" this issue :)

ah you already got it [in your answer](https://github.com/chises/zabbix-nakivo/issues/6#issuecomment-1414190784 ) :)

**Comment by chises** [comment]
> sorry i have make mistake. i should use ./nakivo.sh instead of sh nakivo.sh. now its start script correctly. but when you are testing script from cli you should enter 4 parameters, last one should be job OR repository
> 
> event that now I got timedout:
> 
> connecttimedout(SocketTimeoutException)
> 
> port 4443 as parameter I hardcoded to script
@mrowec 
Port 4443 is the default port, so no update to the script required. Please check if the cli.sh (the script that has been copied from the nakivo server):
`/usr/lib/zabbix/externalscripts/cli.sh --job-list --host 192.168.2.14 --username admin --password 'PASSWORD'`
You should get a list with jobs. 
If you need to change the Port for the nakivo server add the --port parameter:
`/usr/lib/zabbix/externalscripts/cli.sh **--port 4444** --job-list --host 192.168.2.14 --username admin --password 'PASSWORD'`

If you need to adjust the port parameter in the script check line [4](https://github.com/chises/zabbix-nakivo/blob/d01e3963b3fd0a094beb7a0f48c6517ba0fa6882/nakivo.sh#L4) and [6](https://github.com/chises/zabbix-nakivo/blob/d01e3963b3fd0a094beb7a0f48c6517ba0fa6882/nakivo.sh#L6)
and add _--port 4444_
Example:
```
4: /usr/lib/zabbix/externalscripts/cli.sh **--port 4444** --job-list --host $1 --username $2 --password $3 | tr , . | sed -r 's/ *\| */,/g' | sed 's/^ *//;s/ *$//'
6: output=$(/usr/lib/zabbix/externalscripts/cli.sh **--port 4444** --repository-list --host $1 --username $2 --password $3 | tr , . | sed -r 's/  +//g' | sed -r 's/ *: */:/g' | sed -e 's/^[ \t]*//')
```
I will add a optional paramter to the script in the future if the port is not 4443. But you can modify it by yourself as describe above :) let me know if it is working.

**Comment by chises** [comment]
Added custom port support via macro and shell check: https://github.com/chises/zabbix-nakivo/commit/2ecd879d84b85336e7fca208dd41a5d93b43d241
